export default {
	TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
	SHOW_PAGE_TITLE: "SHOW_PAGE_TITLE",
	REQUEST_MAP_VECTOR: "REQUEST_MAP_VECTOR",
	INVALIDATE_MAP_VECTOR: "INVALIDATE_MAP_VECTOR",
	RECEIVE_MAP_VECTOR: "RECEIVE_MAP_VECTOR",
	ERROR_REQUEST_PAGE: "ERROR_REQUEST_PAGE",
	FILTER: {
		BY_COUNTRY: "BY_COUNTRY",
		BY_GROUND: "BY_GROUND",
		BY_SOURCE: "BY_SOURCE",
		BY_VERTICAL_RATE: "BY_VERTICAL_RATE",
		BY_SPI: "BY_SPI",
		BY_BARO_ALT: "BY_BARO_ALT",
		BY_VELOCITY: "BY_VELOCITY",
		BY_GEO_ALT: "BY_GEO_ALT",
		RE_FILTER: "RE_FILTER"
	},
	REQUEST_PLANE_INFO: "REQUEST_PLANE_INFO",
    RECEIVE_PLANE_INFO: "RECEIVE_PLANE_INFO"
};